name: Sync Labels
on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - opened
      - labeled

# Declare default permissions as read only.
permissions: read-all

jobs:
  labels:
    # yamllint disable-line rule:line-length
    uses: outoforbitdev/reusable-workflows-library/.github/workflows/label-manager.yml@8295ba5d1bed3f265c2f3b64ccbde40a1dc0c52e # outoforbitdev/reusable-workflows-library#97
    permissions:
      issues: write
