name: Release App
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Github Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Create Release
        uses: outoforbitdev/action-release-changelog@v0.0.10
        id: semantic-release
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          repository: ${{ github.repository }}
